# fly.toml app configuration file generated for pb-jboxapp on 2024-06-11T18:39:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pb-jboxapp'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
